[package]
name = "rbe"
version = "0.1.0"
authors = ["Scott McLeod <halcyonblue@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
